[package]
name = "builder"
version = "0.1.0"
edition = "2024"

[dependencies]
convert_case = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[lib]
proc-macro = true
[features]
default = ["inference"]
inference = []
